version: '3'

services:
  workoutapi:
    build:
      context: ../.
      dockerfile: docker/Dockerfile.devcontainer
    volumes:
      - .:/workoutapi

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: workout
      POSTGRES_USER: workout
      POSTGRES_DB: workout
    ports:
      - '5432:5432'
